server:
  port: 8000
spring:
  datasource:
    password: kevintam
    username: root
    url: jdbc:mysql://localhost:3306/movie_film?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: log-movie-provider