server:
  port: 9004
spring:
  application:
    name: movie-msm-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/movie_film?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: kevintam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    username: 843808107@qq.com
    password:
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
#    开启加密使用
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  httpclient:
    connection-timeout: 60000